import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const content = JSON.parse(fs.readFileSync(path.join(root,'content/content.json'),'utf8'));
const dist = path.join(root,'dist');
fs.rmSync(dist,{recursive:true,force:true});
fs.mkdirSync(dist,{recursive:true});
copyDir(path.join(root,'public'),dist);

const locales = Object.keys(content.locales);
const baseUrl = 'https://dealtravel.hr';

const esc = s => String(s ?? '').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const icon = (name, cls='') => {
  const common=`class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"`;
  const map={
    phone:`<svg ${common}><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.8 19.8 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.12 4.18 2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.12.9.33 1.78.62 2.63a2 2 0 0 1-.45 2.11L8 9.73a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.85.29 1.73.5 2.63.62A2 2 0 0 1 22 16.92z"/></svg>`,
    mail:`<svg ${common}><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></svg>`,
    pin:`<svg ${common}><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>`,
    car:`<svg ${common}><path d="M5 17h14M6 17v2M18 17v2M4 14l1.5-5h13L20 14M6 9l1-3h10l1 3M5 14h2M17 14h2"/><rect x="4" y="10" width="16" height="7" rx="2"/></svg>`,
    bus:`<svg ${common}><rect x="5" y="3" width="14" height="16" rx="2"/><path d="M8 19v2M16 19v2M8 7h8M8 11h8M8 15h.01M16 15h.01"/></svg>`,
    sparkles:`<svg ${common}><path d="m12 3-1.5 3.5L7 8l3.5 1.5L12 13l1.5-3.5L17 8l-3.5-1.5L12 3Z"/><path d="m5 14-.9 2.1L2 17l2.1.9L5 20l.9-2.1L8 17l-2.1-.9L5 14ZM19 13l-.7 1.6-1.6.7 1.6.7.7 1.6.7-1.6 1.6-.7-1.6-.7L19 13Z"/></svg>`,
    driver:`<svg ${common}><circle cx="12" cy="8" r="3"/><path d="M5 21v-2a7 7 0 0 1 14 0v2M8 13l4 3 4-3M9 4l3-2 3 2"/></svg>`,
    arrow:`<svg ${common}><path d="M5 12h14M14 7l5 5-5 5"/></svg>`,
    shield:`<svg ${common}><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></svg>`,
    clock:`<svg ${common}><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>`,
    globe:`<svg ${common}><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18"/></svg>`
  };
  return map[name]||map.arrow;
};

function copyDir(src,dst){
  fs.mkdirSync(dst,{recursive:true});
  for(const ent of fs.readdirSync(src,{withFileTypes:true})){
    const s=path.join(src,ent.name), d=path.join(dst,ent.name);
    ent.isDirectory()?copyDir(s,d):fs.copyFileSync(s,d);
  }
}
function write(rel,html){const p=path.join(dist,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,html)}
function localePath(locale,p=''){return `/${locale}/${p}`.replace(/\/+/g,'/').replace(/\/\/$/,'/');}
function langAlternates(pagePath=''){
  return locales.map(l=>`<link rel="alternate" hreflang="${l}" href="${baseUrl}${localePath(l,pagePath)}">`).join('\n')+`\n<link rel="alternate" hreflang="x-default" href="${baseUrl}${localePath('hr',pagePath)}">`;
}
function schemaOrg(locale){const s=content.settings;const region={hr:"Istra",en:"Istria",de:"Istrien",nl:"Istrië"}[locale]||"Istria";const country={hr:"Hrvatska",en:"Croatia",de:"Kroatien",nl:"Kroatië"}[locale]||"Croatia";const europe={hr:"Europa",en:"Europe",de:"Europa",nl:"Europa"}[locale]||"Europe";return `<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"LocalBusiness","name":"DEAL","url":baseUrl,"telephone":s.phone,"email":s.email,"address":{"@type":"PostalAddress","addressRegion":region,"addressCountry":"HR"},"areaServed":[region,country,europe]})}</script>`}
function header(locale,active='home'){
  const c=content.copy[locale], s=content.settings;
  const divisionIds=['taxi','travel','clean','drivers'];
  const simpleBefore=[['home','',c.nav.home]];
  const simpleAfter=[['about','o-nama/',c.nav.about],...(content.pages||[]).filter(p=>p.nav).map(p=>['custom:'+p.slug,p.slug+'/',p.title[locale]]),['contact','kontakt/',c.nav.contact]];
  const simpleLink=([id,p,label])=>`<a class="nav-top-link ${active===id?'active':''}" href="/${locale}/${p}">${esc(label)}</a>`;
  const dropdown=id=>{
    const d=content.divisions.find(x=>x.id===id);
    const label=c.nav[id];
    const submenu=[...(content.items[id]||[]).map(item=>({label:item.title[locale],path:`${d.path}/${item.slug}/`}))];
    if(id==='taxi') submenu.push({label:c.nav.fleet,path:'vozni-park/'});
    const items=submenu.map((item,index)=>`<a class="submenu-link" href="/${locale}/${item.path}"><span class="submenu-index">${String(index+1).padStart(2,'0')}</span><span class="submenu-label">${esc(item.label)}</span><span class="submenu-arrow" aria-hidden="true">↗</span></a>`).join('');
    return `<div class="nav-item nav-dropdown ${active===id?'active':''}"><div class="nav-parent-row"><a class="nav-top-link ${active===id?'active':''}" href="/${locale}/${d.path}/">${esc(label)}</a><button class="submenu-toggle" type="button" aria-expanded="false" aria-label="${esc(label)}"><span aria-hidden="true"></span></button></div><div class="nav-submenu"><div class="submenu-head"><span class="submenu-kicker">DEAL</span><strong>${esc(d.titles[locale].replace(/^DEAL\s+/i,''))}</strong></div><div class="submenu-list">${items}</div></div></div>`;
  };
  const navHtml=[...simpleBefore.map(simpleLink),...divisionIds.map(dropdown),...simpleAfter.map(simpleLink)].join('');
  return `<header class="site-header"><div class="nav-shell"><a class="brand" href="/${locale}/" aria-label="DEAL"><img src="/assets/images/logo.svg" alt="DEAL"></a><nav class="nav-links" aria-label="${esc(c.mainNavigation)}">${navHtml}<div class="mobile-languages" aria-label="${esc(c.languageSelector)}">${locales.map(l=>`<a class="${locale===l?'active':''}" data-locale="${l}" href="/${l}/"><span>${content.locales[l].flag}</span><strong>${content.locales[l].label}</strong></a>`).join('')}</div></nav><div class="nav-actions"><a class="phone-mini" href="tel:${s.phone}" aria-label="${esc(s.phoneDisplay)}">${icon('phone')}<span class="phone-copy"><strong>${esc(s.phoneDisplay)}</strong><span class="phone-status">24/7 ${locale==='hr'?'dostupan':locale==='de'?'erreichbar':locale==='nl'?'bereikbaar':'available'}</span></span></a><div class="lang"><button class="lang-toggle" type="button" aria-label="${esc(c.languageLabel)}"><span>${content.locales[locale].flag}</span>${content.locales[locale].label} ▾</button><div class="lang-menu">${locales.map(l=>`<a data-locale="${l}" href="/${l}/"><span>${content.locales[l].flag}</span>${content.locales[l].name}</a>`).join('')}</div></div><a class="btn btn-outline" href="/${locale}/kontakt/">${esc(c.ctaButton)}</a><button class="menu-toggle" type="button" aria-label="${esc(c.menuLabel)}" aria-expanded="false"><span></span></button></div></div></header>`;
}
function intro(locale){const c=content.copy[locale];return `<div class="intro"><div class="intro-mark"><img src="/assets/images/logo.svg" alt=""><span class="intro-line"></span><span class="intro-caption">${esc(c.introCaption)}</span></div></div>`}
function mobileBar(locale){const c=content.copy[locale],s=content.settings;return `<div class="mobile-bar"><a href="tel:${s.phone}">${icon('phone')}${esc(c.call)}</a><a href="https://wa.me/${s.whatsapp.replace(/\D/g,'')}" target="_blank" rel="noopener">${esc(c.whatsapp)}</a></div>`}
function cookie(locale){const c=content.copy[locale];return `<aside class="cookie-banner" aria-live="polite"><h3>${esc(c.cookieBannerTitle)}</h3><p>${esc(c.cookieBannerText)}</p><div class="cookie-actions"><button class="btn btn-primary" data-cookie-all>${esc(c.cookieAccept)}</button><button class="btn btn-outline" data-cookie-necessary>${esc(c.cookieNecessary)}</button></div></aside>`}
function footer(locale){const c=content.copy[locale],s=content.settings;return `<footer class="site-footer"><div class="container"><div class="footer-grid"><div><img class="footer-logo" src="/assets/images/logo.svg" alt="DEAL"><p class="footer-desc">${esc(c.footerText)}</p></div><div><div class="footer-title">${esc(c.nav.home)}</div><div class="footer-links"><a href="/${locale}/taxi-transfers/">${esc(c.nav.taxi)}</a><a href="/${locale}/travel/">${esc(c.nav.travel)}</a><a href="/${locale}/clean/">${esc(c.nav.clean)}</a><a href="/${locale}/najam-vozaca/">${esc(c.nav.drivers)}</a><a href="/${locale}/vozni-park/">${esc(c.nav.fleet)}</a></div></div><div><div class="footer-title">${esc(c.nav.contact)}</div><div class="contact-row">${icon('phone')}<a href="tel:${s.phone}">${esc(s.phoneDisplay)}</a></div><div class="contact-row">${icon('mail')}<a href="mailto:${s.email}">${esc(s.email)}</a></div><div class="contact-row">${icon('pin')}<span>${esc(s.locationLocalized?.[locale]||s.location)}<br>${esc(s.coverageLocalized?.[locale]||s.coverage)}</span></div></div><div><div class="footer-title">DEAL</div><div class="footer-links"><a href="/${locale}/o-nama/">${esc(c.nav.about)}</a><a href="/${locale}/kontakt/">${esc(c.nav.contact)}</a><a href="/${locale}/politika-privatnosti/">${esc(c.privacy)}</a><a href="/${locale}/kolacici/">${esc(c.cookies)}</a></div></div></div><div class="footer-bottom"><span>© 2026 DEAL. ${esc(c.rights)}</span><div class="footer-legal"><a href="/${locale}/politika-privatnosti/">${esc(c.privacy)}</a><a href="/${locale}/kolacici/">${esc(c.cookies)}</a></div></div></div></footer>`}
function shell(locale,title,description,body,active='home',pagePath=''){
  const analytics=esc(content.settings.analyticsId);
  return `<!doctype html><html lang="${locale}" data-analytics="${analytics}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | DEAL</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#05080a"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="canonical" href="${baseUrl}${localePath(locale,pagePath)}">${langAlternates(pagePath)}<link rel="stylesheet" href="/assets/css/styles.css">${schemaOrg(locale)}</head><body>${intro(locale)}${header(locale,active)}${body}${footer(locale)}${mobileBar(locale)}${cookie(locale)}<script src="/assets/js/main.js" defer></script></body></html>`;
}
function divisionCard(locale,d,i){const c=content.copy[locale];const title=d.titles[locale];let normal='',highlight=title;if(title.startsWith('DEAL ')){normal='DEAL';highlight=title.slice(5)}else if(title.includes('DEAL ')){const k=title.indexOf('DEAL ');normal=title.slice(0,k).trim();highlight=title.slice(k)}return `<a class="service-card reveal reveal-delay-${i}" href="/${locale}/${d.path}/"><div class="service-card-bg" style="background-image:url('${d.image}')"></div><div class="service-card-content"><div class="service-icon">${icon(d.icon)}</div><h3>${normal?esc(normal)+' ':''}<span>${esc(highlight)}</span></h3><p>${esc(d.descriptions[locale])}</p><span class="btn">${esc(c.readMore)} ${icon('arrow')}</span></div></a>`}
function featureCard(locale,type,item){const c=content.copy[locale];const base=content.divisions.find(d=>d.id===type)?.path || type;return `<article class="feature-card reveal"><div class="feature-img"><img src="${item.image}" alt="${esc(item.title[locale])}" loading="lazy"></div><div class="feature-body"><span class="tag">${esc(content.divisions.find(d=>d.id===type)?.titles[locale]||'DEAL')}</span><h3>${esc(item.title[locale])}</h3><p>${esc(item.excerpt[locale])}</p><a class="text-link" href="/${locale}/${base}/${item.slug}/">${esc(c.readMore)}</a></div></article>`}
function home(locale){const c=content.copy[locale];const featured=[...content.items.taxi.filter(x=>x.featured).slice(0,1).map(x=>['taxi',x]),...content.items.travel.filter(x=>x.featured).slice(0,2).map(x=>['travel',x])];return shell(locale,c.homeTitle,c.heroText,`
<section class="hero"><div class="hero-bg"></div><div class="hero-grid"><div class="container"><div class="hero-center"><img class="hero-logo-mark" src="/assets/images/mark.svg" alt="DEAL"><div class="eyebrow" style="justify-content:center">${esc(c.heroEyebrow)}</div><h1 class="hero-title">${esc(c.heroTitle)}</h1><div class="hero-subtitle">${esc(c.heroSubtitle)}</div><p class="hero-copy">${esc(c.heroText)}</p><div class="hero-actions"><a class="btn btn-primary" href="#services">${esc(c.heroPrimary)} ${icon('arrow')}</a><a class="btn btn-outline" href="/${locale}/kontakt/">${esc(c.heroSecondary)}</a></div></div></div></div><div class="scroll-cue">${esc(c.scrollLabel)}</div></section>
<section class="section" id="services"><div class="container"><div class="service-intro"><div><div class="eyebrow">${esc(c.serviceIntroKicker)}</div><h2>${esc(c.serviceIntroTitle)}</h2></div><p class="lead">${esc(c.serviceIntroText)}</p></div><div class="service-grid">${content.divisions.map((d,i)=>divisionCard(locale,d,i)).join('')}</div></div></section>
<section class="section-tight"><div class="container"><div class="why-layout"><div class="why-visual reveal"><div class="why-badge"><span class="eyebrow">DEAL</span><strong>${esc(c.whyTitle)}</strong></div></div><div class="why-content reveal"><div class="eyebrow">${esc(c.whyKicker)}</div><h2>${esc(c.whyTitle)}</h2><p class="lead">${esc(c.whyText)}</p><div class="why-list">${c.whyItems.map((x,i)=>`<div class="why-item"><strong>${esc(x[0])}</strong><p>${esc(x[1])}</p></div>`).join('')}</div></div></div></div></section>
<section class="section"><div class="container"><div class="section-header"><div><div class="eyebrow">${esc(c.featuredKicker)}</div><h2>${esc(c.featuredTitle)}</h2><p class="lead">${esc(c.featuredText)}</p></div><a class="btn btn-outline" href="/${locale}/travel/">${esc(c.viewAll)}</a></div><div class="feature-grid">${featured.map(([t,x])=>featureCard(locale,t,x)).join('')}</div></div></section>
<section class="section-tight"><div class="container"><div class="fleet-wrap reveal"><div class="fleet-head"><div><div class="eyebrow">${esc(c.fleetKicker)}</div><h2>${esc(c.fleetTitle)}</h2></div><p class="lead">${esc(c.fleetText)}</p></div><div class="fleet-grid">${content.fleet.map(f=>`<article class="fleet-card"><img src="${f.image}" alt="${esc(f.name)}" loading="lazy"><div class="fleet-card-info"><span class="eyebrow">${esc(c.fleetBrandLabel)}</span><h3>${esc(f.name)}</h3><p class="muted">${esc(f.type[locale])}</p><div class="fleet-meta"><span>${esc(typeof f.capacity==='object'?f.capacity[locale]:f.capacity)}</span></div></div></article>`).join('')}</div></div></div></section>
<section class="section driver-section"><div class="container"><div class="driver-card reveal"><div class="driver-copy"><div class="eyebrow">${esc(c.driverKicker)}</div><h2>${esc(c.driverTitle)}</h2><p class="lead">${esc(c.driverText)}</p><div class="driver-columns"><div class="driver-mini"><strong>${esc(c.forDrivers)}</strong><p>${esc(content.items.drivers[0].excerpt[locale])}</p></div><div class="driver-mini"><strong>${esc(c.forCompanies)}</strong><p>${esc(content.items.drivers[1].excerpt[locale])}</p></div></div><div class="hero-actions" style="justify-content:flex-start"><a class="btn btn-primary" href="/${locale}/najam-vozaca/for-drivers/">${esc(c.apply)}</a><a class="btn btn-outline" href="/${locale}/najam-vozaca/for-companies/">${esc(c.request)}</a></div></div><div class="driver-visual"></div></div></div></section>
<section class="section-tight"><div class="container"><div class="cta-panel reveal"><div><h3>${esc(c.ctaTitle)}</h3><p>${esc(c.ctaText)}</p></div><a class="btn btn-primary" href="/${locale}/kontakt/">${esc(c.ctaButton)} ${icon('arrow')}</a></div></div></section>
`,'home','');}
function divisionPage(locale,id){const c=content.copy[locale], d=content.divisions.find(x=>x.id===id), items=content.items[id]||[];const title=d.titles[locale],desc=d.descriptions[locale];const active=id==='drivers'?'drivers':id;return shell(locale,title,desc,`
<section class="page-hero"><div class="page-hero-bg" style="background-image:url('${d.image}')"></div><div class="container"><div class="page-hero-content"><div class="eyebrow">DEAL</div><h1>${esc(title)}</h1><p>${esc(desc)}</p><div class="hero-actions" style="justify-content:flex-start"><a class="btn btn-primary" href="/${locale}/kontakt/?service=${id}">${esc(c.ctaButton)}</a></div></div></div></section>
<section class="section"><div class="container"><div class="section-header"><div><div class="eyebrow">${esc(c.serviceIntroKicker)}</div><h2>${esc(c.serviceIntroTitle)}</h2></div><p class="lead">${esc(c.serviceIntroText)}</p></div><div class="inner-grid">${items.map(item=>featureCard(locale,id,item)).join('')}</div></div></section>
<section class="section-tight"><div class="container"><div class="stat-strip reveal"><div class="stat"><strong>24/7</strong><span>${esc(c.whyItems[0][0])}</span></div><div class="stat"><strong>4</strong><span>HR · EN · DE · NL</span></div><div class="stat"><strong>DEAL</strong><span>${esc(c.premiumStandard)}</span></div><div class="stat"><strong>EU</strong><span>${esc(c.whyItems[3][0])}</span></div></div></div></section>
<section class="section-tight"><div class="container"><div class="cta-panel"><div><h3>${esc(c.ctaTitle)}</h3><p>${esc(c.ctaText)}</p></div><a class="btn btn-primary" href="/${locale}/kontakt/?service=${id}">${esc(c.ctaButton)} ${icon('arrow')}</a></div></div></section>
`,active,d.path+'/');}
function detailPage(locale,id,item){const c=content.copy[locale],d=content.divisions.find(x=>x.id===id);const title=item.title[locale],desc=item.excerpt[locale];return shell(locale,title,desc,`
<section class="page-hero"><div class="page-hero-bg" style="background-image:url('${item.image}')"></div><div class="container"><div class="page-hero-content"><h1>${esc(title)}</h1><p>${esc(desc)}</p></div></div></section>
<section class="section"><div class="container"><div class="content-layout"><article class="prose reveal"><div class="eyebrow">${esc(d.titles[locale])}</div><h2>${esc(title)}</h2><p class="lead">${esc(item.body[locale])}</p><h2>${esc(c.whyTitle)}</h2><p>${esc(c.whyText)}</p><div class="why-list">${c.whyItems.map(x=>`<div class="why-item"><strong>${esc(x[0])}</strong><p>${esc(x[1])}</p></div>`).join('')}</div></article><aside><div class="side-card"><div class="eyebrow">DEAL</div><h3>${esc(c.ctaTitle)}</h3><p>${esc(c.ctaText)}</p><a class="btn btn-primary" href="/${locale}/kontakt/?service=${id}&interest=${encodeURIComponent(item.slug)}">${esc(c.ctaButton)}</a><a class="btn btn-outline" style="margin-top:8px" href="tel:${content.settings.phone}">${esc(c.call)} ${content.settings.phoneDisplay}</a></div></aside></div></div></section>
`,id==='drivers'?'drivers':id,`${d.path}/${item.slug}/`)}
function aboutPage(locale){const c=content.copy[locale];return shell(locale,c.nav.about,c.pageAboutText,`
<section class="page-hero"><div class="page-hero-bg" style="background-image:url('/assets/images/about-coast.avif')"></div><div class="container"><div class="page-hero-content"><div class="eyebrow">DEAL</div><h1>${esc(c.pageAboutTitle)}</h1><p>${esc(c.pageAboutText)}</p></div></div></section>
<section class="section"><div class="container"><div class="why-layout"><div class="why-content reveal"><div class="eyebrow">${esc(c.standardLabel)}</div><h2>${esc(c.whyTitle)}</h2><p class="lead">${esc(c.whyText)}</p><div class="why-list">${c.whyItems.map(x=>`<div class="why-item"><strong>${esc(x[0])}</strong><p>${esc(x[1])}</p></div>`).join('')}</div></div><div class="why-visual reveal"></div></div></div></section>
`,'about','o-nama/');}
function fleetPage(locale){const c=content.copy[locale];return shell(locale,c.nav.fleet,c.fleetText,`
<section class="page-hero"><div class="page-hero-bg" style="background-image:url('/assets/images/fleet-bus.avif')"></div><div class="container"><div class="page-hero-content"><div class="eyebrow">${esc(c.fleetBrandLabel)}</div><h1>${esc(c.fleetPageTitle)}</h1><p>${esc(c.fleetText)}</p></div></div></section>
<section class="section"><div class="container"><div class="fleet-wrap"><div class="fleet-grid" style="margin-top:0">${content.fleet.map(f=>`<article class="fleet-card"><img src="${f.image}" alt="${esc(f.name)}"><div class="fleet-card-info"><span class="eyebrow">${esc(f.type[locale])}</span><h3>${esc(f.name)}</h3><p>${esc(c.fleetText)}</p><div class="fleet-meta"><span>${esc(typeof f.capacity==='object'?f.capacity[locale]:f.capacity)}</span></div></div></article>`).join('')}</div></div></div></section>
`,'taxi','vozni-park/');}
function contactPage(locale){const c=content.copy[locale],s=content.settings;const options=content.divisions.map(d=>`<option value="${d.id}">${esc(d.titles[locale])}</option>`).join('');return shell(locale,c.nav.contact,c.contactText,`
<section class="page-hero"><div class="page-hero-bg" style="background-image:url('/assets/images/about-coast.avif')"></div><div class="container"><div class="page-hero-content"><div class="eyebrow">${esc(c.contactBrandLabel)}</div><h1>${esc(c.contactTitle)}</h1><p>${esc(c.contactText)}</p></div></div></section>
<section class="section"><div class="container"><div class="contact-grid"><div class="contact-panel reveal"><div class="eyebrow">DEAL</div><h2 style="font-size:48px">${esc(c.nav.contact)}</h2><p class="lead">${esc(c.contactText)}</p><div class="contact-list"><div class="contact-item"><div class="contact-ico">${icon('phone')}</div><div><span>${esc(c.call)}</span><strong><a href="tel:${s.phone}">${esc(s.phoneDisplay)}</a></strong></div></div><div class="contact-item"><div class="contact-ico">${icon('mail')}</div><div><span>E-mail</span><strong><a href="mailto:${s.email}">${esc(s.email)}</a></strong></div></div><div class="contact-item"><div class="contact-ico">${icon('pin')}</div><div><span>DEAL</span><strong>${esc(s.locationLocalized?.[locale]||s.location)} · ${esc(s.coverageLocalized?.[locale]||s.coverage)}</strong></div></div></div></div><div class="contact-panel reveal"><form data-enquiry-form data-success="${esc(c.form.success)}" data-error="${esc(c.form.error)}"><input type="hidden" name="locale" value="${locale}"><div class="form-grid"><div class="field"><label>${esc(c.form.name)}</label><input name="name" required autocomplete="name"></div><div class="field"><label>${esc(c.form.email)}</label><input name="email" type="email" required autocomplete="email"></div><div class="field"><label>${esc(c.form.phone)}</label><input name="phone" autocomplete="tel"></div><div class="field"><label>${esc(c.form.service)}</label><select name="service"><option value="">—</option>${options}</select></div><div class="field full"><label>${esc(c.form.message)}</label><textarea name="message" required></textarea></div><div class="field full"><p class="form-note">${esc(c.form.consent)}</p><button class="btn btn-primary contact-submit" type="submit"><span>${esc(c.form.send)}</span>${icon('arrow')}</button><div class="form-status"></div></div></div></form></div></div></div></section>
`,'contact','kontakt/');}
function customPage(locale,page){const c=content.copy[locale];const title=page.title[locale],desc=page.excerpt[locale];return shell(locale,title,desc,`
<section class="page-hero"><div class="page-hero-bg" style="background-image:url('${page.image}')"></div><div class="container"><div class="page-hero-content"><div class="eyebrow">DEAL</div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div></div></section>
<section class="section"><div class="container"><div class="content-layout"><article class="prose"><h2>${esc(title)}</h2>${String(page.body[locale]||'').split(/\n+/).filter(Boolean).map(p=>`<p>${esc(p)}</p>`).join('')}</article><aside><div class="side-card"><div class="eyebrow">DEAL</div><h3>${esc(c.ctaTitle)}</h3><p>${esc(c.ctaText)}</p><a class="btn btn-primary" href="/${locale}/kontakt/">${esc(c.ctaButton)}</a></div></aside></div></div></section>
`,'custom:'+page.slug,page.slug+'/')}
function legalPage(locale,type){
  const c=content.copy[locale], privacy=type==='privacy', title=privacy?c.privacy:c.cookies;
  const legal={
    hr:{privacy:["DEAL obrađuje samo podatke koji su potrebni za odgovor na upit, organizaciju usluge i ispunjenje zakonskih obveza. Podaci iz kontakt obrasca ne koriste se za automatizirano profiliranje.","Podatke ne prodajemo trećim stranama. Kada je za izvršenje usluge potreban partner, dijeli se samo opseg podataka nužan za dogovorenu uslugu.","Za pristup, ispravak ili brisanje svojih podataka možete se javiti na e-mail naveden na ovoj stranici."],cookies:["Stranica koristi nužne kolačiće za osnovnu funkcionalnost i pohranu vašeg izbora privatnosti.","Analitički kolačići uključuju se samo uz privolu i samo ako je analitika konfigurirana. Svoj izbor možete promijeniti brisanjem postavki preglednika za ovu domenu.","Vanjske usluge, poput WhatsAppa, otvaraju se tek nakon vaše radnje i podliježu pravilima privatnosti tih pružatelja."]},
    en:{privacy:["DEAL processes only the information required to respond to an enquiry, organise a service and meet applicable legal obligations. Contact-form data is not used for automated profiling.","We do not sell personal data. Where a service partner is required, only the minimum information necessary to deliver the agreed service is shared.","You can request access, correction or deletion of your data through the e-mail address shown on this website."],cookies:["This website uses essential cookies for core functionality and to remember your privacy choice.","Analytics cookies are enabled only with consent and only when analytics has been configured. You can reset your choice by clearing this site's browser storage.","External services such as WhatsApp open only after your action and are subject to the privacy terms of those providers."]},
    de:{privacy:["DEAL verarbeitet nur Daten, die zur Beantwortung einer Anfrage, zur Organisation einer Leistung und zur Erfüllung gesetzlicher Pflichten erforderlich sind. Daten aus dem Kontaktformular werden nicht für automatisiertes Profiling verwendet.","Personenbezogene Daten werden nicht verkauft. Ist für die Leistung ein Partner erforderlich, werden nur die dafür notwendigen Informationen weitergegeben.","Auskunft, Berichtigung oder Löschung Ihrer Daten können Sie über die auf dieser Website angegebene E-Mail-Adresse anfordern."],cookies:["Diese Website verwendet notwendige Cookies für die Grundfunktionen und zur Speicherung Ihrer Datenschutzauswahl.","Analyse-Cookies werden nur nach Einwilligung und nur bei konfigurierter Analyse aktiviert. Ihre Auswahl kann durch Löschen der Website-Daten im Browser zurückgesetzt werden.","Externe Dienste wie WhatsApp werden erst nach Ihrer Aktion geöffnet und unterliegen den Datenschutzbestimmungen des jeweiligen Anbieters."]},
    nl:{privacy:["DEAL verwerkt alleen gegevens die nodig zijn om een aanvraag te beantwoorden, een dienst te organiseren en aan wettelijke verplichtingen te voldoen. Gegevens uit het contactformulier worden niet gebruikt voor geautomatiseerde profilering.","Persoonsgegevens worden niet verkocht. Wanneer een partner nodig is voor de uitvoering van een dienst, delen we alleen de minimaal noodzakelijke informatie.","U kunt inzage, correctie of verwijdering van uw gegevens aanvragen via het e-mailadres op deze website."],cookies:["Deze website gebruikt noodzakelijke cookies voor de basisfunctionaliteit en om uw privacykeuze te onthouden.","Analytische cookies worden alleen na toestemming en alleen wanneer analytics is geconfigureerd geactiveerd. U kunt uw keuze resetten door de websitegegevens in uw browser te wissen.","Externe diensten zoals WhatsApp worden pas na uw actie geopend en vallen onder het privacybeleid van die aanbieders."]}
  };
  const paras=legal[locale][privacy?'privacy':'cookies'];
  return shell(locale,title,paras[0],`<section class="page-hero" style="min-height:50svh"><div class="page-hero-bg" style="background-image:url('/assets/images/about-coast.avif')"></div><div class="container"><div class="page-hero-content"><div class="eyebrow">DEAL</div><h1>${esc(title)}</h1></div></div></section><section class="section"><div class="container"><article class="prose" style="max-width:820px"><h2>${esc(title)}</h2>${paras.map(p=>`<p>${esc(p)}</p>`).join('')}<p><strong>${esc(c.nav.contact)}:</strong> <a class="copper" href="mailto:${content.settings.email}">${content.settings.email}</a></p></article></div></section>`,'home',privacy?'politika-privatnosti/':'kolacici/');
}

for(const locale of locales){
  write(`${locale}/index.html`,home(locale));
  for(const id of ['taxi','travel','clean','drivers']){
    const d=content.divisions.find(x=>x.id===id); write(`${locale}/${d.path}/index.html`,divisionPage(locale,id));
    for(const item of content.items[id]||[]) write(`${locale}/${d.path}/${item.slug}/index.html`,detailPage(locale,id,item));
  }
  write(`${locale}/o-nama/index.html`,aboutPage(locale));
  write(`${locale}/vozni-park/index.html`,fleetPage(locale));
  write(`${locale}/kontakt/index.html`,contactPage(locale));
  write(`${locale}/politika-privatnosti/index.html`,legalPage(locale,'privacy'));
  write(`${locale}/kolacici/index.html`,legalPage(locale,'cookies'));
  for(const page of (content.pages||[])) write(`${locale}/${page.slug}/index.html`,customPage(locale,page));
}
write('index.html',`<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=/hr/"><link rel="canonical" href="${baseUrl}/hr/"></head><body></body></html>`);

// sitemap
const urls=[];
for(const locale of locales){
  const base=[`${locale}/`,`$LOCALE/taxi-transfers/`,`$LOCALE/travel/`,`$LOCALE/clean/`,`$LOCALE/najam-vozaca/`,`$LOCALE/o-nama/`,`$LOCALE/vozni-park/`,`$LOCALE/kontakt/`,`$LOCALE/politika-privatnosti/`,`$LOCALE/kolacici/`].map(x=>x.replace('$LOCALE',locale));
  urls.push(...base);
  for(const id of ['taxi','travel','clean','drivers']){const d=content.divisions.find(x=>x.id===id);for(const item of content.items[id]||[])urls.push(`${locale}/${d.path}/${item.slug}/`)}
  for(const page of (content.pages||[])) urls.push(`${locale}/${page.slug}/`);
}
write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${baseUrl}/${u}</loc><changefreq>weekly</changefreq><priority>${u.split('/').length<=3?'0.8':'0.7'}</priority></url>`).join('')}</urlset>`);
write('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${baseUrl}/sitemap.xml\n`);
console.log(`Built ${urls.length} localized URLs into ${dist}`);
